[pytest]
testpaths = WEEK1_AES_GCM/tests WEEK2_FPE_PII_PROTECTION/tests WEEK3_POST_QUANTUM_KYBER/tests
python_files = test_*.py
addopts = -ra --import-mode=importlib
pythonpath = . WEEK1_AES_GCM WEEK2_FPE_PII_PROTECTION WEEK3_POST_QUANTUM_KYBER
